name: ray

on:
  schedule:
    - cron: '0 15 * * *'
  pull_request:
    paths:
      - 'ray/**'
      - '.github/workflows/ray.yml'

jobs:
  examples:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2
    - name: setup-python${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install (Python)
      run: |
        python -m pip install --upgrade pip
        pip install --progress-bar off -U setuptools
        pip install git+https://github.com/optuna/optuna.git
        python -c 'import optuna'
    - name: Run examples
      run: |
        python -m py_compile ray/ray_joblib.py  # due to difficulty importing, compile only
      env:
        OMP_NUM_THREADS: 1
